
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyrpumeexjndeurxhisd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cnB1bWVleGpuZGV1cnhoaXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODU2MDYsImV4cCI6MjA1Nzk2MTYwNn0.R0Sy77RnNP9s8WAcEFRS6hrOseyqi5lhcPcMLS9KIks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
